### ISSUE TITLE
Change all capital letters on buttons to lowercase

### ISSUE THREAD

**Issue by danielapizzurro** [matthewmorek/wfp-careers#4]
- Button/CTA "View Job Opportunities" in the splash section
- Button "Read more" in the Humanitarian in action section

**Comment by matthewmorek** [comment]
@danielapizzurro Can I ask for the reason behind it? As part of WFP UI, we generally capitalise button labels. Is it just a stylistic change request?

**Comment by danielapizzurro** [comment]
@matthewmorek I was more concerned about consistency of button labels across the site; the career search and topic page for e.g. use lowercase. 
In addition to consistency, there is also readability to consider; capitalize letter slows down the reading process, so I would still opt for lowercase.

**Comment by matthewmorek** [comment]
I generally agree about maintaining the consistency, but there are a few other points to consider:
- All-caps affects readability when coupled with long-form text, not when used for short text labels or single-line titles; caps work incredibly well at very small and very large font sizes [source](http://practicaltypography.com/all-caps.html);
- All-caps have been deliberately set for buttons used on special sections, such as splash screens, hero images, etc, where they grab more attention;
- Consistency for consistency's own sake leads to homogenous interfaces where everything has the same approximate level of importance, which leads to confusion (which we don't want).

If you still want me to de-emphasise these buttons, they've been taken are of.
