### ISSUE TITLE
text too close to borders on tablet/mobile size 

### ISSUE THREAD

**Issue by danielapizzurro** [matthewmorek/wfp-careers#6]
I've noticed that both on mobile and tablet size, the text in some sections is too close to borders. 
PS. tested with Chrome inspect for iPad/iphone 6/iphone 5/galaxy S5 
![tablet](https://cloud.githubusercontent.com/assets/19909772/17898166/05ba5754-6957-11e6-8413-36d72532598d.PNG)

**Comment by danielapizzurro** [comment]
It still seems too close particularly the header (top-left) and both sides of the three-pieces bar (see screenshots). 
![text on iphone](https://cloud.githubusercontent.com/assets/19909772/17998211/74526ec2-6b73-11e6-9310-c1e2c0192855.PNG)
![text on ipad](https://cloud.githubusercontent.com/assets/19909772/17998214/77783406-6b73-11e6-9a52-c35b93e008fe.PNG)

**Comment by matthewmorek** [comment]
I'll investigate and see how we can improve these.
