### ISSUE TITLE
Stretched images on IE

### ISSUE THREAD

**Issue by danielapizzurro** [matthewmorek/wfp-careers#7]
Images (in particular the first and the second one) appear stretched on IE 11 (desktop). 
 
![images issue](https://cloud.githubusercontent.com/assets/19909772/17900494/d9046836-695f-11e6-903a-3e444466aa0f.PNG)

**Comment by matthewmorek** [comment]
This is due to supplied images not adhering to required dimensions. We can only crop them to match exactly the target area.

IE11, or even Edge 14 [do not support `object-fit` property](http://caniuse.com/#feat=object-fit), which is what other browser use to make sure images fit properly within a container.

**Comment by andrewholgate** [comment]
Here is the current list of agreed image sizes for the new WFP: https://gist.github.com/andrewholgate/68207cf11351c9e48d3ceb7872413790

What size do these images need to be?

**Comment by matthewmorek** [comment]
@andrewholgate These do not fall into the same category, as they are not any of these. The images for this section by default are `384 x 256` (3:2), so it would be good to add this to your list of standard image sizes. We can then simply scale them up/down as needed.

**Comment by andrewholgate** [comment]
So if there isn't standard solution for browsers that do not support `object-fit`, we'll need to use a workaround (unless we want to gain entrance into image-resize-hell).

Which workaround do you propose, [something like this](https://medium.com/@primozcigler/neat-trick-for-css-object-fit-fallback-on-edge-and-other-browsers-afbc53bbb2c3)?
