### ISSUE TITLE
Do not wrap the word 'countries'  

### ISSUE THREAD

**Issue by danielapizzurro** [matthewmorek/wfp-careers#8]
Any way we can get the word *countries* not wrapped to a new line? PS. this is only for `xl` viewport as it looks good at every other one
![countries](https://cloud.githubusercontent.com/assets/19909772/18442222/3d8e9c94-7910-11e6-99eb-951c1aa692e9.PNG)

**Comment by matthewmorek** [comment]
Fixed in ec26035919270fccb5a85f45b10f9c9994954793.
